name: appreposteria
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.3.0
  firebase_auth: ^1.4.1
  firebase_storage: ^8.1.3
  cloud_firestore: ^2.2.2
  image_picker: ^0.7.4
  cached_network_image: ^3.0.0
  simple_animations: ^3.1.1
  mdi: ^5.0.0-nullsafety.0
  feature_discovery: ^0.14.0
  get: ^4.1.4
  logger: ^1.0.0
  path: ^1.8.0
  awesome_dialog: ^2.1.0
  uuid: ^3.0.4
  modal_bottom_sheet: ^2.0.0
  pull_to_refresh: ^2.0.0
  flutter_launcher_icons: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

 
  uses-material-design: true

  assets:
    - images/welcome.png
    - images/login.png
    - images/admin.png
    - images/cash.png
    - images/Autentication.png
    - images/Add_products.png
    - images/Add_User.png
    - images/Apreciation.png
    - images/Checklist.png
    - images/Completed.png
    - images/Confirmed.png
    - images/Directions.png
    - images/empty_cart.png
    - images/Empty_Orders.png
    - images/male_avatar.png
    - images/No_data.png
    - images/On_way.png
    - images/Order_Confirmed.png
    - images/Photos.png
    - images/Shopping_App.png
    - images/male_avatar.png

flutter_icons:
  image_path: 'images/welcome.png'
  android: true
  ios: true